import random
import datetime

# ── Fake dark web mentions ────────────────────────────────
DARK_WEB_MENTIONS = [
    {
        "id": "dw001",
        "forum": "BreachForums",
        "onion": "breachforums3mt2ou.onion",
        "category": "Database Leak",
        "title": "Thomas Cook Travel — Customer Database 2026",
        "preview": "Selling fresh dump of thomascook.com customer DB. 45,000 records including passport numbers, credit cards, booking history...",
        "threat_level": "CRITICAL",
        "price": "$2,500 USD",
        "seller": "d4rkh4x0r_99",
        "date": "2026-03-08",
        "verified": True,
        "records": "45,231 records",
        "contains": ["Full names", "Passport numbers", "Credit cards", "Email addresses", "Phone numbers", "Booking history"],
    },
    {
        "id": "dw002",
        "forum": "RaidForums Mirror",
        "onion": "raidforums2x7bfzk.onion",
        "category": "Credentials",
        "title": "thomascook.com Staff Login Credentials",
        "preview": "Got admin panel creds for Thomas Cook travel portal. Works as of yesterday. Includes 3 admin accounts...",
        "threat_level": "CRITICAL",
        "price": "$800 USD",
        "seller": "cr3d_h4rv3st3r",
        "date": "2026-03-10",
        "verified": False,
        "records": "3 admin + 47 staff accounts",
        "contains": ["Admin credentials", "Staff emails", "VPN access", "Internal system access"],
    },
    {
        "id": "dw003",
        "forum": "XSS.is",
        "onion": "xssforumv3isucukbxhdhwz67hoa5e67hjodzfo7lwoarysea6w7jiad.onion",
        "category": "Vulnerability",
        "title": "[0day] SQL Injection in thomascook.com booking system",
        "preview": "Found critical SQLi in the booking endpoint. Can dump entire customer table. PoC included for buyers...",
        "threat_level": "HIGH",
        "price": "$1,200 USD",
        "seller": "sqli_master_v2",
        "date": "2026-03-05",
        "verified": True,
        "records": "Full DB access",
        "contains": ["SQL injection PoC", "Database schema", "Sample data dump"],
    },
    {
        "id": "dw004",
        "forum": "Telegram Channel",
        "onion": "t.me/darkleaks_official",
        "category": "Data Leak",
        "title": "Free leak — thomascook employee emails + passwords",
        "preview": "Sharing for free: 234 employee email:password combos from Thomas Cook. Most still active. Enjoy...",
        "threat_level": "HIGH",
        "price": "FREE",
        "seller": "an0n_l3ak3r",
        "date": "2026-03-01",
        "verified": False,
        "records": "234 employee accounts",
        "contains": ["Employee emails", "Plaintext passwords", "Department info"],
    },
    {
        "id": "dw005",
        "forum": "HackForums",
        "onion": "hackforums5waqjvri.onion",
        "category": "Source Code",
        "title": "Thomas Cook internal booking system source code",
        "preview": "Got the backend source code for thomascook.com. Flask app, includes DB connection strings and API keys...",
        "threat_level": "HIGH",
        "price": "$3,000 USD",
        "seller": "c0d3_th13f",
        "date": "2026-02-28",
        "verified": False,
        "records": "~15,000 lines of code",
        "contains": ["Flask source code", "Database credentials", "AWS API keys", "Payment gateway keys"],
    },
    {
        "id": "dw006",
        "forum": "Dark Web Monitoring Alert",
        "onion": "darkwebmonitor7f3k.onion",
        "category": "Brand Mention",
        "title": "thomascook.com mentioned in carding tutorial",
        "preview": "New carding guide mentions Thomas Cook as easy target. Weak CVV verification on booking form...",
        "threat_level": "MEDIUM",
        "price": "N/A",
        "seller": "c4rd3r_pro",
        "date": "2026-02-20",
        "verified": False,
        "records": "N/A",
        "contains": ["Carding tutorial", "Payment bypass method"],
    },
    {
        "id": "dw007",
        "forum": "Exploit.in",
        "onion": "exploitinqx57r.onion",
        "category": "Phishing Kit",
        "title": "Thomas Cook phishing kit v2.1 — updated 2026",
        "preview": "Updated phishing kit for thomascook.com. Looks identical to real site. Includes credential harvester...",
        "threat_level": "MEDIUM",
        "price": "$150 USD",
        "seller": "ph1sh_k1ng",
        "date": "2026-02-15",
        "verified": True,
        "records": "N/A",
        "contains": ["Phishing HTML pages", "Credential harvester", "Email templates", "Hosting guide"],
    },
    {
        "id": "dw008",
        "forum": "Nulled.to",
        "onion": "nulledforumx5c5cr.onion",
        "category": "API Keys",
        "title": "Leaked: thomascook Razorpay + Stripe live keys",
        "preview": "Found exposed .env file on thomascook subdomain. Live payment gateway keys inside. Act fast before rotated...",
        "threat_level": "CRITICAL",
        "price": "$500 USD",
        "seller": "k3y_hunt3r",
        "date": "2026-03-09",
        "verified": True,
        "records": "3 payment gateway keys",
        "contains": ["Razorpay live keys", "Stripe secret keys", "AWS credentials"],
    },
]

# ── Threat summary ────────────────────────────────────────
def get_dark_web_summary():
    critical = sum(1 for m in DARK_WEB_MENTIONS if m["threat_level"] == "CRITICAL")
    high     = sum(1 for m in DARK_WEB_MENTIONS if m["threat_level"] == "HIGH")
    medium   = sum(1 for m in DARK_WEB_MENTIONS if m["threat_level"] == "MEDIUM")
    verified = sum(1 for m in DARK_WEB_MENTIONS if m["verified"])

    return {
        "total":          len(DARK_WEB_MENTIONS),
        "critical":       critical,
        "high":           high,
        "medium":         medium,
        "verified":       verified,
        "last_seen":      "2026-03-10",
        "risk_score":     95,
        "mentions":       DARK_WEB_MENTIONS,
        "forums_found":   list(set(m["forum"] for m in DARK_WEB_MENTIONS)),
        "categories":     list(set(m["category"] for m in DARK_WEB_MENTIONS)),
    }
